repos:
  # Basic sanity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key

  # Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        files: ^app/Dockerfile$

  # Node.js / TypeScript formatting & linting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.1.0"]
        files: \.(js|ts|tsx|json|md|yaml|yml)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^app/.*\.(js|ts|tsx)$
        additional_dependencies:
          - eslint@8.56.0
          - eslint-plugin-import@2.29.1
          - eslint-plugin-jsx-a11y@6.8.0
          - eslint-plugin-react@7.33.2
          - eslint-plugin-react-hooks@4.6.0
