name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Python (needed for pre-commit itself)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install pre-commit
      - run: pip install pre-commit

      # Run pre-commit on all files
      - run: pre-commit run --all-files --show-diff-on-failure
